### ISSUE TITLE
Consider whether or not we want --upgrade

### ISSUE THREAD

**Issue by zancas** [f5devcentral/f5-openstack-ansible#21]
Do we really want to run `--upgrade` here:

https://github.com/f5devcentral/f5-openstack-ansible/blob/liberty/playbooks/roles/install_f5_heat_plugins/tasks/main.yml#L7

?

**Comment by zancas** [comment]
Or here:

https://github.com/f5devcentral/f5-openstack-ansible/blob/liberty/playbooks/roles/install_lbaasv2_driver/tasks/main.yml#L28

**Comment by zancas** [comment]
Or here:

https://github.com/f5devcentral/f5-openstack-ansible/blob/liberty/playbooks/roles/install_lbaasv2_agent/tasks/main.yml#L31

**Comment by zancas** [comment]
Hi there @pjbreaux do you receive notifications when new issues are created on this repo?

**Comment by pjbreaux** [comment]
I do.

**Comment by pjbreaux** [comment]
The --upgrade can be removed on almost all, except the install_lbaasv2_agent task.

**Comment by pjbreaux** [comment]
Except the last one, https://github.com/f5devcentral/f5-openstack-ansible/blob/liberty/playbooks/roles/install_lbaasv2_agent/tasks/main.yml#L31

That should remain, or we should provide an option for a user to provide additional arguments to the pip install if they wish.

**Comment by mattgreene** [comment]
@zancas @pjbreaux : Is there technical work as an outcome of this discussion, or can we close the issue?

**Comment by pjbreaux** [comment]
There is, and we don't want to upgrade by default. I'll make the fix for this. Not today, but likely next week.

**Comment by adam-f5** [comment]
Repository Archived
