### ISSUE TITLE
Make the microservice/Dockerfile be built upon an alpine linux image.

### ISSUE THREAD

**Issue by zancas** [f5devcentral/f5-openstack-ansible#23]
This work requires that the "FROM" directive in the Dockerfile be changed such that the `<tag>` element specifies an `alpine linux` python3.6 image.

To accomplish this:

* resolve this bug https://github.com/docker-library/python/issues/155
* change the `apt install` to the appropriate `apk add` directive

**Comment by adam-f5** [comment]
Repository Archived
