### ISSUE TITLE
Package location variables point to Mitaka instead of Liberty

### ISSUE THREAD

**Issue by mattgreene** [f5devcentral/f5-openstack-ansible#4]
#### Operating System
N/A

#### OpenStack Release
Liberty

#### Description
The following files reference Mitaka instead of Liberty, for package installation:
playbooks/vars/agent_deploy_vars.yaml
playbooks/vars/agent_driver_deploy_vars.yaml
playbooks/vars/driver_deploy_vars.yaml

Versions will move forward over time, but should at least point to a version from the correct branch (i.e. 8.1.0)

**Comment by adam-f5** [comment]
Repository Archived
